ARCHETYPES: dict[str, dict] = {
    "TruthSeeker": {
        "trait_vector": {"openness": 0.85, "conscientiousness": 0.75, "extraversion": 0.55,
                         "agreeableness": 0.60, "neuroticism": 0.25, "moral_rigidity": 0.40, "susceptibility": 0.45},
        "moral_alignment": "utilitarian",
        "appeal_type": "rational",
        "beliefs": [
            "Evidence and data should guide decisions",
            "Scientific consensus deserves serious weight",
            "Complex problems require nuanced solutions",
            "Intellectual honesty matters more than tribal loyalty",
        ],
    },
    "AuthorityDeferrer": {
        "trait_vector": {"openness": 0.30, "conscientiousness": 0.80, "extraversion": 0.45,
                         "agreeableness": 0.75, "neuroticism": 0.30, "moral_rigidity": 0.75, "susceptibility": 0.60},
        "moral_alignment": "authoritarian",
        "appeal_type": "authority",
        "beliefs": [
            "Institutions exist for good reason",
            "Social order prevents chaos",
            "Experts and leaders should be trusted",
            "Rules protect everyone equally",
        ],
    },
    "Rebel": {
        "trait_vector": {"openness": 0.80, "conscientiousness": 0.35, "extraversion": 0.70,
                         "agreeableness": 0.20, "neuroticism": 0.55, "moral_rigidity": 0.65, "susceptibility": 0.30},
        "moral_alignment": "libertarian",
        "appeal_type": "emotional",
        "beliefs": [
            "Government overreach threatens freedom",
            "Individual choice is sacred",
            "The establishment cannot be trusted",
            "Resistance to control is a virtue",
        ],
    },
    "Pragmatist": {
        "trait_vector": {"openness": 0.60, "conscientiousness": 0.70, "extraversion": 0.50,
                         "agreeableness": 0.55, "neuroticism": 0.30, "moral_rigidity": 0.35, "susceptibility": 0.55},
        "moral_alignment": "utilitarian",
        "appeal_type": "rational",
        "beliefs": [
            "Practical outcomes matter more than ideology",
            "Compromise is not weakness",
            "Context determines what is right",
            "Short-term sacrifice can yield long-term gain",
        ],
    },
    "Idealist": {
        "trait_vector": {"openness": 0.70, "conscientiousness": 0.65, "extraversion": 0.60,
                         "agreeableness": 0.65, "neuroticism": 0.45, "moral_rigidity": 0.85, "susceptibility": 0.30},
        "moral_alignment": "deontological",
        "appeal_type": "emotional",
        "beliefs": [
            "Principles must never be compromised for convenience",
            "Justice is non-negotiable",
            "Rights are inherent, not granted",
            "Moral clarity requires courage",
        ],
    },
    "Manipulator": {
        "trait_vector": {"openness": 0.65, "conscientiousness": 0.55, "extraversion": 0.80,
                         "agreeableness": 0.15, "neuroticism": 0.35, "moral_rigidity": 0.20, "susceptibility": 0.20},
        "moral_alignment": "nihilist",
        "appeal_type": "social",
        "beliefs": [
            "Power determines outcomes, not truth",
            "People are motivated by self-interest",
            "Perception is more important than reality",
            "Strategic ambiguity is a useful tool",
        ],
    },
    "Conformist": {
        "trait_vector": {"openness": 0.30, "conscientiousness": 0.60, "extraversion": 0.55,
                         "agreeableness": 0.80, "neuroticism": 0.50, "moral_rigidity": 0.40, "susceptibility": 0.85},
        "moral_alignment": "authoritarian",
        "appeal_type": "social",
        "beliefs": [
            "Going along with the group is usually the safe choice",
            "Social harmony matters",
            "If everyone does it, it must be acceptable",
            "Standing out invites trouble",
        ],
    },
    "EmotionalReactor": {
        "trait_vector": {"openness": 0.55, "conscientiousness": 0.35, "extraversion": 0.65,
                         "agreeableness": 0.50, "neuroticism": 0.90, "moral_rigidity": 0.45, "susceptibility": 0.70},
        "moral_alignment": "deontological",
        "appeal_type": "emotional",
        "beliefs": [
            "Feelings are valid data points",
            "Personal experience is the most honest guide",
            "Compassion should drive policy",
            "Emotional truth matters as much as logical truth",
        ],
    },
    "CommunityBuilder": {
        "trait_vector": {"openness": 0.65, "conscientiousness": 0.70, "extraversion": 0.80,
                         "agreeableness": 0.85, "neuroticism": 0.30, "moral_rigidity": 0.35, "susceptibility": 0.50},
        "moral_alignment": "utilitarian",
        "appeal_type": "social",
        "beliefs": [
            "We are stronger together",
            "Bridges matter more than walls",
            "Everyone deserves to be heard",
            "Collective wellbeing requires individual sacrifice",
        ],
    },
    "Cynic": {
        "trait_vector": {"openness": 0.35, "conscientiousness": 0.45, "extraversion": 0.40,
                         "agreeableness": 0.20, "neuroticism": 0.60, "moral_rigidity": 0.55, "susceptibility": 0.25},
        "moral_alignment": "nihilist",
        "appeal_type": "rational",
        "beliefs": [
            "Nothing will fundamentally change",
            "Those in power serve themselves",
            "Good intentions produce bad outcomes",
            "Skepticism is the only honest position",
        ],
    },
}
